### ISSUE TITLE
What is the currency of displayed costs?

### ISSUE THREAD

**Issue by romanr** [vantage-sh/handbook.vantage.sh#24]
Searched everywhere. Except for Dollar sign `$` there is no mention of which country dollar that is. Can anyone clarify?

**Comment by EverettBerry** [comment]
It's the US Dollar because by default all AWS bills are in USD, https://aws.amazon.com/premiumsupport/knowledge-center/non-us-currency/

**Comment by vansia43** [comment]
Thanks for pointing this out! Added note to address this and make it more clear: #38.
