### ISSUE TITLE
Update Slack link on pages

### ISSUE THREAD

**Issue by vansia43** [vantage-sh/handbook.vantage.sh#39]
Update Slack link per https://vantagesh.slack.com/archives/C01T1QYLY06/p1698089833069809 as old one is out of date. Also can fix formatting on some of the notes that are out of the box like here: https://handbook.vantage.sh/tools/cost-reports/.

**Comment by EverettBerry** [comment]
Please use https://vantage.sh/slack for this. And I know this isn't the place for this but let's have that in the docs too.

**Comment by vansia43** [comment]
Yep! The redirect is the one I am doing. I just linked the convo Dann and I had about it above :-)
